version: '3.5'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        SSG_REVALIDATE: ${SSG_REVALIDATE}
    volumes:
      - ./app:/app
      - /app/.next
      - /app/node_modules
      - ./.cache/app/yarn:/usr/local/share/.cache/yarn
      - ./.cache/app/npm:/root/.npm
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - BUILD_PATH_MODE=production
      - APP_PREFIX=${APP_PREFIX}
      - APP_URL=https://moov-song.make-project.fun/fansreport/2022
      - API_URL=https://moov-song.make-project.fun/fansreport/2022/api
    command: npm run staging

